In [95]:
import sys

import gym
import matplotlib.pyplot as plt
import numpy as np
import random

In [108]:
env = gym.make("CartPole-v1", render_mode="human")
print(env.action_space)
print(env.observation_space)
print(env.action_space.sample())

Discrete(2)
Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
1


In [109]:
env.reset()

done = False
while not done:
    env.render()
    obs, rew, terminated, truncated , info = env.step(env.action_space.sample())
    done = truncated or terminated
    print(f"{obs} -> {rew}")
env.close()

print(env.observation_space.low)
print(env.observation_space.high)

[ 0.00294108 -0.24426086 -0.03384449  0.29928648] -> 1.0
[-0.00194414 -0.04867325 -0.02785876 -0.00387531] -> 1.0
[-0.00291761 -0.24338481 -0.02793627  0.2798893 ] -> 1.0
[-0.0077853  -0.43809736 -0.02233848  0.56363195] -> 1.0
[-0.01654725 -0.2426692  -0.01106584  0.2639959 ] -> 1.0
[-0.02140063 -0.43763146 -0.00578592  0.55316806] -> 1.0
[-0.03015326 -0.24242873  0.00527744  0.25866786] -> 1.0
[-0.03500184 -0.04738252  0.01045079 -0.03234584] -> 1.0
[-0.03594949  0.14758801  0.00980388 -0.3217132 ] -> 1.0
[-0.03299773 -0.04767217  0.00336961 -0.0259547 ] -> 1.0
[-0.03395117 -0.24284229  0.00285052  0.26778945] -> 1.0
[-0.03880802 -0.04776113  0.00820631 -0.02399303] -> 1.0
[-0.03976324  0.14724219  0.00772645 -0.3140755 ] -> 1.0
[-0.0368184  -0.04798898  0.00144494 -0.01896596] -> 1.0
[-0.03777818  0.14711222  0.00106562 -0.31119263] -> 1.0
[-0.03483593  0.34221897 -0.00515823 -0.6035393 ] -> 1.0
[-0.02799155  0.14716955 -0.01722902 -0.31248558] -> 1.0
[-0.02504816 -0.04770277 -0.023